### ISSUE TITLE
Show error splash screen for hard errors on app start

### ISSUE THREAD

**Issue by antoniave** [open-pioneer/trails-core-packages#68]
Show an error screen in the UI when the app cannot start.

The error screen should show an user-friendly error message (in English). If possible, the message should be shown in German if that's the requested language. 

If in dev mode, the screen should also show the actual technical error message. 

~~Consider to allow the developer to provide own error screen component.~~ --> not yet implemented

**Comment by antoniave** [comment]
Dev Branch: https://github.com/open-pioneer/trails-core-packages/tree/feature/error-screen

**Comment by antoniave** [comment]
PR: https://github.com/open-pioneer/trails-core-packages/pull/71

**Comment by mbeckem** [comment]
Sample App: https://open-pioneer.github.io/trails-demo/core-packages/samples/error-sample/
